### ISSUE TITLE
broadside assumes your targets are in the same cluster

### ISSUE THREAD

**Issue by rfroetscher** [lumoslabs/broadside#38] opened 2016-12-07 18:45 UTC
staging targets have to be in the same cluster as prod targets @matl33t

**Comment by jdoconnor** [comment] 2016-12-07 21:40
can you please elaborate?

**Comment by matl33t** [comment] 2016-12-07 21:54
i believe this is a duplicate of https://github.com/lumoslabs/broadside/issues/5

**Comment by rfroetscher** [comment] 2016-12-07 21:56
oopsie. yes, that's right

**Closed** 2016-12-07 21:57 UTC
